;
; 真空波動研 詳細フォーマット書式指定用ファイル 230101
;
; 黒羽製作所
; https://kurohane.net/
; kurohane@kurohane.net
;
;
;
[RIFF]
;
; 音声がMP3の場合 : [MP3]参照
; 音声がAC3の場合 : [AC3]参照
; 音声がDTSの場合 : [DTS]参照
;
VIDEO	#WIDTH#x#HEIGHT# #BITDEPTH#Bit #CODEC# #FRAMERATE#fps #FRAME#f #BITRATEK#kb/s
AUDIO	#CODEC# #SAMPLERATEK#kHz #BITDEPTH#Bit #CHANNEL#ch #BITRATEK#kb/s
CDDA	Track#TRACK# #DISCID# #HOUR#:#MIN#:#SEC#
EXTWAV	#CODEC# #SAMPLERATEK#kHz #BITDEPTH#Bit #CHANNEL#ch(#CHANNELORDER#) #BITRATEK#kb/s

[REAL]
VIDEO	#WIDTH#x#HEIGHT# #BITDEPTH#Bit #CODEC# #FRAMERATE#fps #BITRATEK#kb/s
AUDIO	#CODEC# #SAMPLERATEK#kHz #BITDEPTH#Bit #CHANNEL#ch #BITRATEK#kb/s

[MPEG1/2]
;
; 音声がMP3の場合 : [MP3]参照
; 音声がAC3の場合 : [AC3]参照
; 音声がAACの場合 : [AAC]参照
; 音声がDTSの場合 : [DTS]参照
;
MPEG1	#WIDTH#x#HEIGHT# #CODEC# #ASPECT# #FRAMERATE#fps #BITRATEK#kb/s #BITRATEMODE#
MPEG2	#WIDTH#x#HEIGHT# #CODEC# #PROFILE# #ASPECT# #INTERLACE# #FRAMERATE#fps #BITRATEK#kb/s #BITRATEMODE#
LPCM	LinearPCM #SAMPLERATEK#kHz #BITDEPTH#Bit #CHANNEL#ch #BITRATEK#kb/s

[QUICKTIME]
;
; 映像がMPEG1/2の場合   : [MPEG1/2]参照
; 映像がAVC/HEVCの場合  : [AVC]参照
; 映像がAV1の場合       : [AV1]参照
; 音声がMP3の場合       : [MP3]参照
; 音声がAC3の場合       : [AC3]参照
; 音声がAACの場合       : [AAC]参照
; 音声がVorbisの場合    : [OGG]参照
; 音声がPureVoiceの場合 : [PUREVOICE]参照
;
VIDEO	#WIDTH#x#HEIGHT# #BITDEPTH#Bit #CODEC# #FRAMERATE#fps #FRAME#f #BITRATEK#kb/s
AUDIO	#CODEC# #SAMPLERATEK#kHz #BITDEPTH#Bit #CHANNEL#ch #BITRATEK#kb/s

[AVC]
;
; HEVCも共用しています
; #BITDEPTH#、#FRAMERATE#、#BITRATEK# はパラメータ次第で0の場合があります 
; #FRAME# はQuickTimeコンテナ格納時以外は0になります
;
VIDEO	#WIDTH#x#HEIGHT# #BITDEPTH#Bit #CODEC# #PROFILE# #ASPECT# #INTERLACE# #FRAMERATE#fps #FRAME#f #BITRATEK#kb/s

[AV1]
;
; #BITDEPTH#、#FRAMERATE#、#BITRATEK# はパラメータ次第で0の場合があります 
; #FRAME# はQuickTimeコンテナ格納時以外は0になります
;
VIDEO	#WIDTH#x#HEIGHT# #BITDEPTH#Bit #CODEC# #PROFILE# #FRAMERATE#fps #FRAME#f #BITRATEK#kb/s

[OGG]
;
; 音声がMP3の場合 : [MP3]参照
; 音声がAC3の場合 : [AC3]参照
; 音声がDTSの場合 : [DTS]参照
;
VIDEO	#WIDTH#x#HEIGHT# #BITDEPTH#Bit #CODEC# #FRAMERATE#fps #FRAME#f
THEORA	#WIDTH#x#HEIGHT# #CODEC# #FRAMERATE#fps #ASPECT# #BITRATEK#kb/s #FRAME#f
VORBIS	Vorbis #SAMPLERATEK#kHz #BITRATEK#kb/s #BITRATEMODE# #CHANNEL#ch
SPEEX	Speex #SAMPLERATEK#kHz #BITRATEK#kb/s #BITRATEMODE# #CHANNEL#ch #COMPTYPE#
OPUS	Opus #SAMPLERATEK#kHz #BITRATEK#kb/s #CHANNEL#ch

[WINDOWSMEDIA]
;
; VIDEO1 : #FRAMERATE# 有り
; VIDEO2 : #FRAMERATE# 無し
;
VIDEO1	#WIDTH#x#HEIGHT# #BITDEPTH#Bit #CODEC# #FRAMERATE#fps #BITRATEK#kb/s
VIDEO2	#WIDTH#x#HEIGHT# #BITDEPTH#Bit #CODEC# #BITRATEK#kb/s
AUDIO	#CODEC# #SAMPLERATEK#kHz #BITDEPTH#Bit #CHANNEL#ch #BITRATEK#kb/s

[MATROSKA]
;
; AUDIOはTTA等、ヘッダを削られてその形式の詳細を使えない場合にのみ使われます。
; 通常はそれぞれの形式の詳細で出ます。
;
VIDEO	#WIDTH#x#HEIGHT# #BITDEPTH#Bit #CODEC# #FRAMERATE#fps
AUDIO	#CODEC# #SAMPLERATEK#kHz #BITDEPTH#Bit #CHANNEL#ch

[FLASHVIDEO]
;
; 音声がMP3の場合 : [MP3]参照
;
FLV		#WIDTH#x#HEIGHT# #CODEC# #FRAMERATE#fps #BITRATEK#kb/s
FLL		#WIDTH#x#HEIGHT# #CODEC# #PROFILE# #FRAMERATE#fps #BITRATEK#kb/s
AUDIO	#CODEC# #SAMPLERATEK#kHz #BITDEPTH#Bit #CHANNEL#ch #BITRATEK#kb/s

[MPEG2-TS]
LPCM	LinearPCM #SAMPLERATEK#kHz #CHANNEL#ch(#CHANNELCONFIG# #CHANNELORDER#) #BITRATEK#kb/s

[AIFF]
AUDIO	#FORMAT# #CODEC# #SAMPLERATEK#kHz #BITDEPTH#Bit #CHANNEL#ch #BITRATEK#kb/s

[MP3]
;
; CBR1 : 裸MP3で総フレーム数が出せる場合
; CBR2 : コンテナ格納時等で総フレーム数が出せない場合
;
CBR1	MPEG#VERSION#-Layer#LAYER# #SAMPLERATEK#kHz #BITRATEK#kb/s #BITRATEMODE# #CHANNEL# #FRAME#f
CBR2	MPEG#VERSION#-Layer#LAYER# #SAMPLERATEK#kHz #BITRATEK#kb/s #BITRATEMODE# #CHANNEL#
VBRI	MPEG#VERSION#-Layer#LAYER# #SAMPLERATEK#kHz #BITRATEK#kb/s #BITRATEMODE# #CHANNEL# #VBRFORMAT# #FRAME#f [Q#VBRI-QR#]
XING	MPEG#VERSION#-Layer#LAYER# #SAMPLERATEK#kHz #BITRATEK#kb/s #BITRATEMODE# #CHANNEL# #VBRFORMAT# #FRAME#f [#ENCNAME#]
LAME	MPEG#VERSION#-Layer#LAYER# #SAMPLERATEK#kHz #BITRATEK#kb/s #BITRATEMODE# #CHANNEL# #VBRFORMAT# #FRAME#f [#LAME-VERSION# #LAME-VBRMODE# #LAME-BITRATEK#kb/s #LAME-CHANNEL#]

[AU]
AUDIO	AU #CODEC# #SAMPLERATEK#kHz #BITDEPTH#Bit #CHANNEL#ch #BITRATEK#kb/s

[MIDI]
;
; AUDIO1 : 曲名が有る場合
; AUDIO2 : 曲名が無い場合
;
AUDIO1	MIDI Format#FORMAT# #TRACK#Track Δ#DELTA# [#TITLE#]
AUDIO2	MIDI Format#FORMAT# #TRACK#Track Δ#DELTA#

[AC3]
AUDIO	#CODEC# #SAMPLERATEK#kHz #CHANNEL#ch(#CHANNELCONFIG# #CHANNELORDER#) #SERVICETYPE# #BITRATEK#kb/s

[APE]
AUDIO	Monkey's Audio #SAMPLERATEK#kHz #BITDEPTH#Bit #CHANNEL#ch #COMPTYPE# #BITRATEK#kb/s #FRAME#f

[MUSEPACK]
AUDIO	MusePack SV#VERSION# #SAMPLERATEK#kHz #BITRATEK#kb/s #CHANNEL#ch

[FLAC]
AUDIO	FLAC #SAMPLERATEK#kHz #BITDEPTH#Bit #CHANNEL#ch #BITRATEK#kb/s

[AAC]
;
; AUDIO1 : 総フレーム数が出せない場合
; AUDIO2 : 総フレーム数が出せる場合 (AACの内部フォーマットによります)
;
AUDIO1	AAC #SAMPLERATEK#kHz #CHANNEL#ch(#CHANNELCONFIG# #CHANNELORDER#) #PROFILE# #BITRATEK#kb/s
AUDIO2	AAC #SAMPLERATEK#kHz #CHANNEL#ch(#CHANNELCONFIG# #CHANNELORDER#) #PROFILE# #BITRATEK#kb/s #FRAME#f

[TTA]
AUDIO	TTA#VERSION# #SAMPLERATEK#kHz #BITDEPTH#Bit #CHANNEL#ch #BITRATEK#kb/s

[VQ]
AUDIO	#CODEC# #SAMPLERATEK#kHz #CHANNEL#ch #BITRATEK#kb/s

[DTS]
;
; AUDIO1 : 通常
; AUDIO2 : VBRやフリーレート等、ビットレートを数値で表さない場合
;
AUDIO1	#VERSION#(#ENDIAN#) #SAMPLERATEK#kHz #BITDEPTH#Bit #CHANNEL#ch(#CHANNELORDER#) #BITRATEK#kb/s
AUDIO2	#VERSION#(#ENDIAN#) #SAMPLERATEK#kHz #BITDEPTH#Bit #CHANNEL#ch(#CHANNELORDER#) #BITRATEK#

[WAVPACK]
;
; FORMATの部分に以下の形式の詳細がそのまま入ります
;
; 音声がWAVの場合        : [RIFF]参照
; 音声がDSF,DSDIFFの場合 : [DSD]参照
;
AUDIO	Wavpack#VERSION# #HYBRID# #FORMAT#

[OPTIMFROG]
AUDIO	OptimFROG(#HYBRID#) #SAMPLERATEK#kHz #BITDEPTH#Bit #CHANNEL#ch #BITRATEK#kb/s [#COMPTYPE#/#COMPSPEED#]

[PUREVOICE]
AUDIO	QUALCOMM PureVoice #CODEC# #SAMPLERATEK#kHz #BITDEPTH#Bit #CHANNEL#ch #BITRATEK#kb/s

[S98]
AUDIO	#DEVICE# #CLOCK#Hz

[DSD]
AUDIO	#FORMAT# #SAMPLERATEM#MHz #BITDEPTH#Bit #CHANNEL#ch(#CHANNELCONFIG# #CHANNELORDER#) #BITRATEK#kb/s

[MSF]
;
; 音声がMP3の場合 : [MP3]参照
;
AUDIO	#CODEC# #SAMPLERATEK#kHz #CHANNEL#ch #BITRATEK#kb/s

[DTS-HD]
AUDIO	#FORMAT# #SAMPLERATEK#kHz #CHANNEL#ch(#CHANNELCONFIG# #CHANNELORDER#) #BITRATEK#kb/s

[ADX]
ADX	ADX #SAMPLERATEK#kHz #BITDEPTH#Bit #CHANNEL#ch #BITRATEK#kb/s
AIX	AIX #SAMPLERATEK#kHz #BITDEPTH#Bit #CHANNEL#ch #BITRATEK#kb/s

[HCA]
AUDIO	HCA#VERSION# #SAMPLERATEK#kHz #CHANNEL#ch #BITRATEK#kb/s

#end
