//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.42000
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace IndigoMovieManager.Properties {


    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.8.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {

        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));

        public static Settings Default {
            get {
                return defaultInstance;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("10, 10")]
        public global::System.Drawing.Point MainLocation {
            get {
                return ((global::System.Drawing.Point)(this["MainLocation"]));
            }
            set {
                this["MainLocation"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("800, 600")]
        public global::System.Drawing.Size MainSize {
            get {
                return ((global::System.Drawing.Size)(this["MainSize"]));
            }
            set {
                this["MainSize"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string LastDoc {
            get {
                return ((string)(this["LastDoc"]));
            }
            set {
                this["LastDoc"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string LastMainDbDialogDirectory {
            get {
                return ((string)(this["LastMainDbDialogDirectory"]));
            }
            set {
                this["LastMainDbDialogDirectory"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("<?xml version=\"1.0\" encoding=\"utf-16\"?>\r\n<ArrayOfString xmlns:xsd=\"http://www.w3." +
            "org/2001/XMLSchema\" xmlns:xsi=\"http://www.w3.org/2001/XMLSchema-instance\">\r\n  <s" +
            "tring />\r\n</ArrayOfString>")]
        public global::System.Collections.Specialized.StringCollection RecentFiles {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["RecentFiles"]));
            }
            set {
                this["RecentFiles"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool AutoOpen {
            get {
                return ((bool)(this["AutoOpen"]));
            }
            set {
                this["AutoOpen"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool ConfirmExit {
            get {
                return ((bool)(this["ConfirmExit"]));
            }
            set {
                this["ConfirmExit"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int DeleteKeyActionMode {
            get {
                return ((int)(this["DeleteKeyActionMode"]));
            }
            set {
                this["DeleteKeyActionMode"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2")]
        public int ShiftDeleteKeyActionMode {
            get {
                return ((int)(this["ShiftDeleteKeyActionMode"]));
            }
            set {
                this["ShiftDeleteKeyActionMode"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public int CtrlDeleteKeyActionMode {
            get {
                return ((int)(this["CtrlDeleteKeyActionMode"]));
            }
            set {
                this["CtrlDeleteKeyActionMode"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\Program Files\\MPC-BE x64\\mpc-be64.exe")]
        public string DefaultPlayerPath {
            get {
                return ((string)(this["DefaultPlayerPath"]));
            }
            set {
                this["DefaultPlayerPath"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("/start <ms>")]
        public string DefaultPlayerParam {
            get {
                return ((string)(this["DefaultPlayerParam"]));
            }
            set {
                this["DefaultPlayerParam"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0.5")]
        public double PlayerVolume {
            get {
                return ((double)(this["PlayerVolume"]));
            }
            set {
                this["PlayerVolume"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("7")]
        public int RecentFilesCount {
            get {
                return ((int)(this["RecentFilesCount"]));
            }
            set {
                this["RecentFilesCount"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool IsResizeThumb {
            get {
                return ((bool)(this["IsResizeThumb"]));
            }
            set {
                this["IsResizeThumb"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("*.avi,*.wmv,*.mpg,*.flv,*.asf,*.mpeg,*.mkv,*.swf,*.ogm,*.mp4,*.mov,*.avs,*.divx,*" +
            ".3gp,*.3g2,*.m4v")]
        public string CheckExt {
            get {
                return ((string)(this["CheckExt"]));
            }
            set {
                this["CheckExt"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("512")]
        public int ThumbnailSlowLaneMinGb {
            get {
                return ((int)(this["ThumbnailSlowLaneMinGb"]));
            }
            set {
                this["ThumbnailSlowLaneMinGb"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("8")]
        public int ThumbnailParallelism {
            get {
                return ((int)(this["ThumbnailParallelism"]));
            }
            set {
                this["ThumbnailParallelism"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1024")]
        public int UpperTabImageCacheMaxEntries {
            get {
                return ((int)(this["UpperTabImageCacheMaxEntries"]));
            }
            set {
                this["UpperTabImageCacheMaxEntries"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2")]
        public int ThumbnailParallelFastRecoveryScaleUpStep {
            get {
                return ((int)(this["ThumbnailParallelFastRecoveryScaleUpStep"]));
            }
            set {
                this["ThumbnailParallelFastRecoveryScaleUpStep"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public int ThumbnailParallelFastRecoveryStableWindows {
            get {
                return ((int)(this["ThumbnailParallelFastRecoveryStableWindows"]));
            }
            set {
                this["ThumbnailParallelFastRecoveryStableWindows"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("12")]
        public int ThumbnailParallelFastRecoveryScaleUpCooldownSec {
            get {
                return ((int)(this["ThumbnailParallelFastRecoveryScaleUpCooldownSec"]));
            }
            set {
                this["ThumbnailParallelFastRecoveryScaleUpCooldownSec"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("15")]
        public int ThumbnailParallelScaleUpBlockedAfterDownSec {
            get {
                return ((int)(this["ThumbnailParallelScaleUpBlockedAfterDownSec"]));
            }
            set {
                this["ThumbnailParallelScaleUpBlockedAfterDownSec"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("180")]
        public int ThumbnailParallelFastRecoveryWindowSec {
            get {
                return ((int)(this["ThumbnailParallelFastRecoveryWindowSec"]));
            }
            set {
                this["ThumbnailParallelFastRecoveryWindowSec"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0.3")]
        public double ThumbnailParallelHighLoadWeightError {
            get {
                return ((double)(this["ThumbnailParallelHighLoadWeightError"]));
            }
            set {
                this["ThumbnailParallelHighLoadWeightError"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0.25")]
        public double ThumbnailParallelHighLoadWeightQueuePressure {
            get {
                return ((double)(this["ThumbnailParallelHighLoadWeightQueuePressure"]));
            }
            set {
                this["ThumbnailParallelHighLoadWeightQueuePressure"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0.2")]
        public double ThumbnailParallelHighLoadWeightSlowBacklog {
            get {
                return ((double)(this["ThumbnailParallelHighLoadWeightSlowBacklog"]));
            }
            set {
                this["ThumbnailParallelHighLoadWeightSlowBacklog"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0.1")]
        public double ThumbnailParallelHighLoadWeightThroughputPenalty {
            get {
                return ((double)(this["ThumbnailParallelHighLoadWeightThroughputPenalty"]));
            }
            set {
                this["ThumbnailParallelHighLoadWeightThroughputPenalty"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0.2")]
        public double ThumbnailParallelHighLoadWeightThermalWarning {
            get {
                return ((double)(this["ThumbnailParallelHighLoadWeightThermalWarning"]));
            }
            set {
                this["ThumbnailParallelHighLoadWeightThermalWarning"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0.1")]
        public double ThumbnailParallelHighLoadWeightUsnMftBusy {
            get {
                return ((double)(this["ThumbnailParallelHighLoadWeightUsnMftBusy"]));
            }
            set {
                this["ThumbnailParallelHighLoadWeightUsnMftBusy"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0.48")]
        public double ThumbnailParallelHighLoadRecoveryThreshold {
            get {
                return ((double)(this["ThumbnailParallelHighLoadRecoveryThreshold"]));
            }
            set {
                this["ThumbnailParallelHighLoadRecoveryThreshold"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0.6")]
        public double ThumbnailParallelHighLoadMildThreshold {
            get {
                return ((double)(this["ThumbnailParallelHighLoadMildThreshold"]));
            }
            set {
                this["ThumbnailParallelHighLoadMildThreshold"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0.82")]
        public double ThumbnailParallelHighLoadThreshold {
            get {
                return ((double)(this["ThumbnailParallelHighLoadThreshold"]));
            }
            set {
                this["ThumbnailParallelHighLoadThreshold"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0.95")]
        public double ThumbnailParallelHighLoadDangerThreshold {
            get {
                return ((double)(this["ThumbnailParallelHighLoadDangerThreshold"]));
            }
            set {
                this["ThumbnailParallelHighLoadDangerThreshold"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool ThumbnailLanePresetInitialized {
            get {
                return ((bool)(this["ThumbnailLanePresetInitialized"]));
            }
            set {
                this["ThumbnailLanePresetInitialized"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool ThumbnailGpuDecodeEnabled {
            get {
                return ((bool)(this["ThumbnailGpuDecodeEnabled"]));
            }
            set {
                this["ThumbnailGpuDecodeEnabled"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool EverythingIntegrationEnabled {
            get {
                return ((bool)(this["EverythingIntegrationEnabled"]));
            }
            set {
                this["EverythingIntegrationEnabled"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public int EverythingIntegrationMode {
            get {
                return ((int)(this["EverythingIntegrationMode"]));
            }
            set {
                this["EverythingIntegrationMode"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("everything")]
        public string FileIndexProvider {
            get {
                return ((string)(this["FileIndexProvider"]));
            }
            set {
                this["FileIndexProvider"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("FiveByTwo")]
        public string DetailThumbnailMode {
            get {
                return ((string)(this["DetailThumbnailMode"]));
            }
            set {
                this["DetailThumbnailMode"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("OsSync")]
        public string ThemeMode {
            get {
                return ((string)(this["ThemeMode"]));
            }
            set {
                this["ThemeMode"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool DebugLogWatchEnabled {
            get {
                return ((bool)(this["DebugLogWatchEnabled"]));
            }
            set {
                this["DebugLogWatchEnabled"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool DebugLogQueueEnabled {
            get {
                return ((bool)(this["DebugLogQueueEnabled"]));
            }
            set {
                this["DebugLogQueueEnabled"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool DebugLogThumbnailEnabled {
            get {
                return ((bool)(this["DebugLogThumbnailEnabled"]));
            }
            set {
                this["DebugLogThumbnailEnabled"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool DebugLogUiEnabled {
            get {
                return ((bool)(this["DebugLogUiEnabled"]));
            }
            set {
                this["DebugLogUiEnabled"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool DebugLogSkinEnabled {
            get {
                return ((bool)(this["DebugLogSkinEnabled"]));
            }
            set {
                this["DebugLogSkinEnabled"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool DebugLogDebugToolEnabled {
            get {
                return ((bool)(this["DebugLogDebugToolEnabled"]));
            }
            set {
                this["DebugLogDebugToolEnabled"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool DebugLogDatabaseEnabled {
            get {
                return ((bool)(this["DebugLogDatabaseEnabled"]));
            }
            set {
                this["DebugLogDatabaseEnabled"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool DebugLogOtherEnabled {
            get {
                return ((bool)(this["DebugLogOtherEnabled"]));
            }
            set {
                this["DebugLogOtherEnabled"] = value;
            }
        }
    }
}
